# Isolate every Dear ImGui public/internal type and helper symbol, not just the
# ImGui namespace. This lets a static mod link its own ImGui without ODR clashes.
$ErrorActionPreference='Stop'
$gyroRoot=Split-Path $PSScriptRoot -Parent
$gyroNames=[Collections.Generic.SortedSet[string]]::new([StringComparer]::Ordinal)
$gyroMacros=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
Get-ChildItem -LiteralPath (Join-Path $gyroRoot 'third_party/imgui') -File -Recurse | Where-Object {$_.Extension -in '.h','.cpp'} | ForEach-Object {
    foreach($gyroMatch in [regex]::Matches([IO.File]::ReadAllText($_.FullName),'\b(?:Im[A-Za-z0-9_]*|imstb_[A-Za-z0-9_]+|stb_[A-Za-z0-9_]+)\b')){
        if($gyroMatch.Value -cnotmatch '^Imm') { [void]$gyroNames.Add($gyroMatch.Value) } # Windows IME API
    }
    foreach($gyroMatch in [regex]::Matches([IO.File]::ReadAllText($_.FullName),'(?m)^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)')){
        [void]$gyroMacros.Add($gyroMatch.Groups[1].Value)
    }
    # Some public typedefs/structs are guarded by their own name so hosts may
    # override them. Defining a rename macro would suppress their declaration.
    foreach($gyroMatch in [regex]::Matches([IO.File]::ReadAllText($_.FullName),'(?:#\s*ifn?def\s+|\bdefined\s*\(?\s*)([A-Za-z_][A-Za-z0-9_]*)')){
        [void]$gyroMacros.Add($gyroMatch.Groups[1].Value)
    }
}
$gyroLines=[Collections.Generic.List[string]]::new()
$gyroLines.Add('#pragma once')
$gyroLines.Add('// Generated by tools/generate_overlay_namespace.ps1 for our bundled ImGui.')
$gyroLines.Add('// All types and helper symbols stay private, including static-link consumers.')
foreach($gyroName in $gyroNames){if(!$gyroMacros.Contains($gyroName)){$gyroLines.Add("#define $gyroName gl_overlay_private_$gyroName")}}
$gyroLines.Add('struct ImGuiContext;')
$gyroLines.Add('extern thread_local ImGuiContext* gl_overlay_imgui_context;')
$gyroLines.Add('#define GImGui gl_overlay_imgui_context')
[IO.File]::WriteAllLines((Join-Path $gyroRoot 'src/detail/overlay_imgui_config.hpp'),$gyroLines,[Text.UTF8Encoding]::new($false))
Write-Output "Isolated $($gyroNames.Count) ImGui identifiers."
