// Generated from localization/*.json. Run tools/generate_localization.ps1 after editing.
#include <algorithm>
#include <cstring>
#include <iterator>
#include <string_view>
namespace gyrolib {
struct Text { const char *language,*key,*value; };
static constexpr Text texts[] = {
{"de","Acceleration","BESCHLEUNIGUNG"},
{"de","ActivationMode","AKTIVIERUNGSMODUS"},
{"de","AimMultiplier","ZIELMULTIPLIKATOR"},
{"de","AltFireMultiplier","MULTIPLIKATOR FÜR ALTERNATIVES FEUER"},
{"de","AutomaticCalibration","KALIBRIERUNG"},
{"de","FlickSpinDurationMs","DREHDAUER"},
{"de","FlickStick","FLICK STICK"},
{"de","GyroButton","TASTEN"},
{"de","GyroEnabled","GYROSKOP"},
{"de","GyroGripSensor","GRIFFSENSOR"},
{"de","GyroSpace","GYRO-BEZUGSRAUM"},
{"de","GyroStick","STICK"},
{"de","GyroStickSensor","STICK-SENSOR"},
{"de","GyroTouchpad","TOUCHPAD"},
{"de","InvertX","X INVERTIEREN"},
{"de","InvertY","Y INVERTIEREN"},
{"de","SensitivityX","EMPFINDLICHKEIT X"},
{"de","SensitivityY","EMPFINDLICHKEIT Y"},
{"de","Smoothing","GLÄTTUNG"},
{"de","acceleration.high","Hoch (3x)"},
{"de","acceleration.low","Niedrig (1,5x)"},
{"de","acceleration.medium","Mittel (2x)"},
{"de","calibration.action","GYRO NEU KALIBRIEREN"},
{"de","calibration.steamHelp","Zum Neukalibrieren dieses Controllers die Steam-Controllereinstellungen verwenden."},
{"de","choice.activation.off","Gyro-Bewegungen deaktivieren."},
{"de","description.Acceleration","Drehe mit schnellen Bewegungen schneller, während langsame Bewegungen präzise bleiben."},
{"de","description.AimMultiplier","Gyro-Empfindlichkeit beim Zielen multiplizieren."},
{"de","description.AltFireMultiplier","Gyro-Empfindlichkeit bei alternativem Feuer anpassen."},
{"de","description.AutomaticCalibration","Wähle, wann ungewollte Bewegungen bei stillgehaltenem Controller korrigiert werden."},
{"de","description.FlickSpinDurationMs","Dauer der anfänglichen Drehung. Bei 0 ms erfolgt sie sofort."},
{"de","description.GyroButton","Wähle die Taste, mit der du das Gyro steuerst."},
{"de","description.GyroEnabled","Steuere Kamera oder Cursor, indem du den Controller drehst."},
{"de","description.GyroGripSensor","Steuere das Gyro durch Berühren des Griffs."},
{"de","description.GyroStick","Steuere das Gyro durch Neigen des Sticks."},
{"de","description.GyroStickSensor","Steuere das Gyro, indem du einen Finger auf den Stick legst, ohne zu klicken."},
{"de","description.GyroTouchpad","Steuere das Gyro durch Berühren des Touchpads."},
{"de","description.InvertX","Horizontale Gyrobewegung umkehren."},
{"de","description.InvertY","Vertikale Gyrobewegung umkehren."},
{"de","description.SensitivityX","Wie weit sich die Ansicht oder der Cursor beim Drehen nach links und rechts bewegt."},
{"de","description.SensitivityY","Wie weit sich die Ansicht oder der Cursor beim Neigen nach oben und unten bewegt."},
{"de","description.Smoothing","Glättet kleines Zittern. Schnelle Bewegungen bleiben direkt. Null deaktiviert die Glättung."},
{"de","description.calibration.cancel","Laufende Kalibrierung stoppen."},
{"de","high","Hoch"},
{"de","low","Niedrig"},
{"de","medium","Mittel"},
{"de","mode.aim","Nur beim Zielen"},
{"de","mode.always","Immer an"},
{"de","mode.hip","Nur ohne Zielen"},
{"de","mode.hold","Zum Aktivieren halten"},
{"de","mode.hold_disable","Zum Deaktivieren halten"},
{"de","mode.toggle","Umschalten"},
{"de","none","Keine"},
{"de","off","Aus"},
{"de","on","Ein"},
{"de","page","GYRO-KONFIGURATION"},
{"de","space.player","Spielerraum"},
{"de","space.roll","Lokale Rollachse"},
{"de","space.world","Weltkoordinaten"},
{"de","space.yaw","Lokale Gierachse"},
{"de","ui.activators","AKTIVATOREN"},
{"en","Acceleration","ACCELERATION"},
{"en","ActivationMode","ACTIVATION MODE"},
{"en","AimMultiplier","AIM MULTIPLIER"},
{"en","AltFireMultiplier","ALT-FIRE MULTIPLIER"},
{"en","AutomaticCalibration","CALIBRATION"},
{"en","FastSensX","FAST SENSITIVITY X"},
{"en","FastSensY","FAST SENSITIVITY Y"},
{"en","FastSpeed","FULL ACCELERATION SPEED"},
{"en","FlickExponent","SHORTEN SMALL PIVOTS"},
{"en","FlickForward","FORWARD TOLERANCE"},
{"en","FlickPadInner","TOUCHPAD RELEASE THRESHOLD"},
{"en","FlickPadOuter","TOUCHPAD START THRESHOLD"},
{"en","FlickSmoothAngle","SMALL TURN LIMIT"},
{"en","FlickSmoothSpeed","SMOOTH LIMIT"},
{"en","FlickSmoothing","SMALL TURN SMOOTHING"},
{"en","FlickSnap","PIVOT DIRECTIONS"},
{"en","FlickSnapStrength","DIRECTION ASSIST STRENGTH"},
{"en","FlickSpinDurationMs","SPIN DURATION"},
{"en","FlickStick","FLICK STICK"},
{"en","FlickStickInner","STICK RELEASE THRESHOLD"},
{"en","FlickStickOuter","STICK START THRESHOLD"},
{"en","FlickStyle","FLICK BEHAVIOR"},
{"en","GyroButton","BUTTONS"},
{"en","GyroEnabled","GYROSCOPE"},
{"en","GyroGripSensor","GRIP SENSOR"},
{"en","GyroSpace","GYRO SPACE"},
{"en","GyroStick","STICK"},
{"en","GyroStickSensor","STICK SENSOR"},
{"en","GyroTouchpad","TOUCHPAD"},
{"en","GyroTrigger","TRIGGERS"},
{"en","HoldInvert","TEMPORARY INVERSION"},
{"en","HoldTrackball","GYRO TRACKBALL"},
{"en","InvertRoll","INVERT ROLL"},
{"en","InvertX","INVERT X"},
{"en","InvertY","INVERT Y"},
{"en","InvertYaw","INVERT YAW"},
{"en","LocalAxisAngle","PRIMARY AXIS OFFSET"},
{"en","LocalRollContribution","COMPLEMENTARY ROLL CONTRIBUTION"},
{"en","RecenterButton","RECENTER CAMERA"},
{"en","RightStickThreshold","STICK DEFLECTION THRESHOLD"},
{"en","SensitivityX","SENSITIVITY X"},
{"en","SensitivityY","SENSITIVITY Y"},
{"en","ShortPress","SHORT PRESS ONLY"},
{"en","SlowSensitivityX","SLOW SENSITIVITY X"},
{"en","SlowSensitivityY","SLOW SENSITIVITY Y"},
{"en","SlowSpeed","ACCELERATION START SPEED"},
{"en","SmoothThreshold","SMOOTHING LIMIT"},
{"en","Smoothing","SMOOTHING"},
{"en","StickEffect","RIGHT STICK EFFECT"},
{"en","TemporaryInvertAxes","INVERTED AXES"},
{"en","TemporaryInvertButton","TEMPORARY INVERSION"},
{"en","Tightening","SMALL MOVEMENT STABILIZATION"},
{"en","TrackballAxes","TRACKBALL AXES"},
{"en","TrackballButton","GYRO TRACKBALL"},
{"en","TrackballDecay","TRACKBALL SLOWDOWN"},
{"en","TriggerThreshold","TRIGGER THRESHOLD"},
{"en","UIScale","INTERFACE SCALE"},
{"en","ZoomCompensation","ADAPT TO ZOOM"},
{"en","acceleration.high","High (3x)"},
{"en","acceleration.low","Low (1.5x)"},
{"en","acceleration.medium","Medium (2x)"},
{"en","anytime","Any time"},
{"en","automatic","Automatic"},
{"en","axes.both","Both"},
{"en","axes.x","Horizontal"},
{"en","axes.y","Vertical"},
{"en","both","Both"},
{"en","button.26","Button 26"},
{"en","button.27","Button 27"},
{"en","button.28","Button 28"},
{"en","button.29","Button 29"},
{"en","button.30","Button 30"},
{"en","button.31","Button 31"},
{"en","button.and"," + "},
{"en","button.back","Back"},
{"en","button.down","D-pad down"},
{"en","button.east","East"},
{"en","button.guide","Guide"},
{"en","button.left","D-pad left"},
{"en","button.left_click","Left stick click"},
{"en","button.left_rear1","Left rear 1"},
{"en","button.left_rear2","Left rear 2"},
{"en","button.left_shoulder","Left shoulder"},
{"en","button.misc1","Misc 1"},
{"en","button.misc2","Misc 2"},
{"en","button.misc3","Misc 3"},
{"en","button.misc4","Misc 4"},
{"en","button.misc5","Misc 5"},
{"en","button.misc6","Misc 6"},
{"en","button.north","North"},
{"en","button.or"," or "},
{"en","button.rear1.both","Both primary rear buttons"},
{"en","button.rear1.either","Either primary rear button"},
{"en","button.rear2.both","Both secondary rear buttons"},
{"en","button.rear2.either","Either secondary rear button"},
{"en","button.right","D-pad right"},
{"en","button.right_click","Right stick click"},
{"en","button.right_rear1","Right rear 1"},
{"en","button.right_rear2","Right rear 2"},
{"en","button.right_shoulder","Right shoulder"},
{"en","button.shoulders.both","Both shoulders"},
{"en","button.shoulders.either","Either shoulder"},
{"en","button.south","South"},
{"en","button.start","Start"},
{"en","button.sticks.both","Both stick clicks"},
{"en","button.sticks.either","Either stick click"},
{"en","button.touchpad","Touchpad click"},
{"en","button.up","D-pad up"},
{"en","button.west","West"},
{"en","calibration.action","Recalibrate gyro"},
{"en","calibration.collecting","Calibrating - keep still"},
{"en","calibration.complete","Calibration complete"},
{"en","calibration.countdown","Calibration in"},
{"en","calibration.moving","Movement detected - keep still to retry"},
{"en","calibration.steamHelp","Calibrate this controller in Steam's controller settings."},
{"en","cancel","Cancel calibration"},
{"en","choice.acceleration.custom","Sensitivity follows your chosen slow and fast values."},
{"en","choice.acceleration.high","Fast turns are up to three times as sensitive."},
{"en","choice.acceleration.low","Fast turns are up to 1.5 times more sensitive."},
{"en","choice.acceleration.medium","Fast turns are up to twice as sensitive."},
{"en","choice.acceleration.off","Keep the same sensitivity at every speed."},
{"en","choice.activation.always","The gyro stays active."},
{"en","choice.activation.hold","Hold the chosen control to turn the gyro on."},
{"en","choice.activation.hold_disable","Hold the chosen control to turn the gyro off."},
{"en","choice.activation.off","Disable gyro rotation."},
{"en","choice.activation.toggle","Use the chosen control to switch the gyro on or off."},
{"en","choice.axes.both","Horizontal and vertical."},
{"en","choice.axes.x","Horizontal only."},
{"en","choice.axes.y","Vertical only."},
{"en","choice.button.on","Use this button to control the gyro."},
{"en","choice.calibration.anytime","Correct drift whenever the controller is still."},
{"en","choice.calibration.menus","Correct drift while the controller is still in a menu."},
{"en","choice.calibration.off","Keep the current calibration."},
{"en","choice.flick.both","Use either the right stick or the right touchpad for quick turns."},
{"en","choice.flick.full","Tilt to pivot, then turn in a circle to rotate."},
{"en","choice.flick.off","Turn off Flick Stick."},
{"en","choice.flick.on","Push the right stick in a direction to face it, then rotate the stick around the edge to keep turning."},
{"en","choice.flick.pivot_only","Tilt to pivot. Circular movements do not turn the camera."},
{"en","choice.flick.rotate_only","Start turning in a circle without an initial pivot."},
{"en","choice.flick.snap45","Guide pivots toward eight directions, including diagonals."},
{"en","choice.flick.snap90","Guide pivots toward forward, back, left or right."},
{"en","choice.flick.snap_off","Use the exact direction you point toward."},
{"en","choice.flick.touchpad","Touch away from the centre of the right touchpad to face that direction, then circle to keep turning."},
{"en","choice.side.both","Use both sides at the same time."},
{"en","choice.side.either","Either side is enough."},
{"en","choice.side.left","Use the left side."},
{"en","choice.side.off","Do not use this control."},
{"en","choice.side.right","Use the right side."},
{"en","choice.space.laser","Aim the front of the controller like a laser pointer."},
{"en","choice.space.local","Adjust how turning and tilting the controller move the view left and right."},
{"en","choice.space.player","Turn left and right relative to the floor. Tilt the controller forwards and backwards to look up and down."},
{"en","choice.space.player_lean","Lean the controller sideways to turn. Tilt it forward or backward to look up or down."},
{"en","choice.space.roll","Turn left and right with the controller's front pointing upward."},
{"en","choice.space.world","Keeps movement aligned with the floor. Looking up and down becomes weaker when the controller is held on its side."},
{"en","choice.space.world_lean","Lean the controller sideways to turn, with vertical aiming adjusted to gravity."},
{"en","choice.space.yaw","Turn the controller left and right, as if it were resting flat on a table."},
{"en","choice.space.yaw_roll","Combine the turning movements of Yaw and Roll."},
{"en","choice.stick.disables","Suspend the gyro while the right stick is tilted."},
{"en","choice.stick.enables","Enable the gyro while the right stick is tilted."},
{"en","choice.touchpad.single_on","Touch the touchpad to activate this control."},
{"en","choice.trigger.left","Use the left trigger."},
{"en","choice.trigger.right","Use the right trigger."},
{"en","context.flick","FLICK STICK GAME MODE"},
{"en","context.gyro","GYRO GAME MODE"},
{"en","context.none","Select a mode"},
{"en","custom","Custom"},
{"en","description.Acceleration","Turn faster with quick controller movements while keeping slow movements precise."},
{"en","description.ActivationMode","Choose when the gyro is active."},
{"en","description.AimMultiplier","Adjust gyro sensitivity while aiming."},
{"en","description.AltFireMultiplier","Adjust gyro sensitivity during Alt-Fire."},
{"en","description.AutomaticCalibration","Choose when to correct movement that happens while the controller is still."},
{"en","description.FastSensX","Horizontal sensitivity for fast movements."},
{"en","description.FastSensY","Vertical sensitivity for fast movements."},
{"en","description.FastSpeed","Above this speed, use the fast sensitivity."},
{"en","description.FlickExponent","Zero uses the same duration for all pivots. One makes a 90° pivot twice as fast as a 180° pivot."},
{"en","description.FlickForward","Pointing within this angle of forward starts circular turning without an initial turn."},
{"en","description.FlickPadInner","Move your finger within this distance from the centre to prepare another flick."},
{"en","description.FlickPadOuter","Touch this far from the centre to start a flick."},
{"en","description.FlickSmoothAngle","Angle changes larger than this limit are not smoothed."},
{"en","description.FlickSmoothSpeed","Circular turns faster than this are not smoothed."},
{"en","description.FlickSmoothing","Softens small steps during circular turning. Higher values make turning smoother but less responsive."},
{"en","description.FlickSnap","Guide the initial turn toward fixed directions."},
{"en","description.FlickSnapStrength","Zero keeps your exact direction. One fully follows the nearest fixed direction."},
{"en","description.FlickSpinDurationMs","How long a flick takes to turn you. At 0 ms, the turn is instant."},
{"en","description.FlickStick","Choose the control used for quick turns."},
{"en","description.FlickStickInner","Return the stick within this distance from the centre to prepare another flick."},
{"en","description.FlickStickOuter","Push the stick this far from the centre to start a flick."},
{"en","description.FlickStyle","Choose an initial pivot, circular turning, or both."},
{"en","description.GyroButton","Choose the button used to control the gyro."},
{"en","description.GyroEnabled","Control the camera or cursor by turning the controller."},
{"en","description.GyroGripSensor","Control the gyro by touching the grip."},
{"en","description.GyroSpace","Choose which controller movements turn the view."},
{"en","description.GyroStick","Control the gyro by tilting the stick."},
{"en","description.GyroStickSensor","Control the gyro by resting a finger on the stick, without clicking."},
{"en","description.GyroTouchpad","Control the gyro by touching the touchpad."},
{"en","description.GyroTrigger","Choose the trigger that controls the gyro."},
{"en","description.HoldInvert","Reverse the gyro direction while holding an activator."},
{"en","description.HoldTrackball","Keep turning while holding an activator to reposition the controller."},
{"en","description.InvertRoll","Reverse left and right for Roll movements."},
{"en","description.InvertX","Reverse left and right."},
{"en","description.InvertY","Reverse up and down."},
{"en","description.InvertYaw","Reverse left and right for Yaw movements."},
{"en","description.LocalAxisAngle","Choose the turn axis: 0 degrees for Yaw, 90 degrees for Roll."},
{"en","description.LocalRollContribution","Mix in more of the second turning motion. Set to 0 to use only the main motion, or a negative value to reverse the added motion."},
{"en","description.RecenterButton","Return the camera to a level view."},
{"en","description.RightStickThreshold","How far you need to tilt the stick before it controls the gyro."},
{"en","description.SensitivityX","How far the view or cursor moves left and right when you turn the controller."},
{"en","description.SensitivityY","How far the view or cursor moves up and down when you tilt the controller."},
{"en","description.ShortPress","A short press triggers the action on release. Holding the button blocks that action."},
{"en","description.SlowSensitivityX","Horizontal sensitivity for slow movements."},
{"en","description.SlowSensitivityY","Vertical sensitivity for slow movements."},
{"en","description.SlowSpeed","Below this speed, use the slow sensitivity."},
{"en","description.SmoothThreshold","Movements faster than this limit are not smoothed."},
{"en","description.Smoothing","Softens small shaky movements. Higher values feel smoother but respond more slowly. Zero responds directly."},
{"en","description.StickEffect","Choose what tilting the right stick does to the gyro."},
{"en","description.TemporaryInvertAxes","Choose which directions to reverse."},
{"en","description.TemporaryInvertButton","Hold this button to reverse the gyro direction."},
{"en","description.Tightening","Reduces tiny movements without blocking them. Zero disables this effect."},
{"en","description.TrackballAxes","Choose which directions keep turning."},
{"en","description.TrackballButton","Hold this button to keep turning while you reposition the controller."},
{"en","description.TrackballDecay","How quickly the turn slows down. Zero keeps its speed; one halves it each second."},
{"en","description.TriggerThreshold","How far to press the trigger to activate it."},
{"en","description.UIScale","Adjust the size of the menu. Automatic adapts to your screen."},
{"en","description.ZoomCompensation","Reduce gyro sensitivity when zooming in."},
{"en","description.calibration","Place the controller on a stable surface and leave it still until calibration finishes."},
{"en","description.calibration.cancel","Stop the calibration in progress."},
{"en","description.context.flick","Choose the game mode that controls flick stick."},
{"en","description.context.gyro","Choose the game mode that controls the gyro."},
{"en","description.context.sensitivity","Adjust gyro sensitivity."},
{"en","description.reset","Restore all settings to their default values."},
{"en","description.save","Save your settings."},
{"en","description.tab.default","Gyro and flick stick settings."},
{"en","description.tab.general","Controller and calibration settings."},
{"en","either","Either"},
{"en","flick.both","Either"},
{"en","flick.full","Pivot and rotate"},
{"en","flick.pivot_only","Pivot only"},
{"en","flick.rotate_only","Rotate only"},
{"en","flick.snap45","45° directions"},
{"en","flick.snap90","90° directions"},
{"en","flick.stick","Stick"},
{"en","flick.touchpad","Touchpad"},
{"en","high","High"},
{"en","left","Left"},
{"en","low","Low"},
{"en","medium","Medium"},
{"en","menus","Menus only"},
{"en","mode.aim","Aim Only"},
{"en","mode.always","Always on"},
{"en","mode.context","Only in this mode"},
{"en","mode.hip","Hip-fire Only"},
{"en","mode.hold","Hold to enable"},
{"en","mode.hold_disable","Hold to disable"},
{"en","mode.outside_context","Except in this mode"},
{"en","mode.toggle","Toggle"},
{"en","none","None"},
{"en","off","Off"},
{"en","on","On"},
{"en","page","GYRO CONFIGURATION"},
{"en","reset","Reset all settings"},
{"en","right","Right"},
{"en","save","Save settings"},
{"en","space.laser","Laser Pointer"},
{"en","space.local","Local Space (Advanced)"},
{"en","space.player","Player Space"},
{"en","space.player_lean","Player Space - Lean"},
{"en","space.roll","Roll"},
{"en","space.world","World Space"},
{"en","space.world_lean","World Space - Lean"},
{"en","space.yaw","Yaw"},
{"en","space.yaw_roll","Yaw + Roll"},
{"en","stick.disables","Disable gyro"},
{"en","stick.enables","Enable gyro"},
{"en","tab.default","Camera"},
{"en","tab.general","General"},
{"en","tab.unavailable","This mode is currently unavailable."},
{"en","trigger.left","Left trigger"},
{"en","trigger.right","Right trigger"},
{"en","ui.activators","ACTIVATORS"},
{"en","ui.advanced","Advanced"},
{"en","ui.advanced.acceleration","Acceleration options."},
{"en","ui.advanced.flick","Flick Stick options."},
{"en","ui.advanced.hold_disable","Temporary inversion and gyro trackball."},
{"en","ui.advanced.modifiers","Right stick options."},
{"en","ui.advanced.smoothing","Smoothing and stabilization options."},
{"en","ui.auto_calibration","Automatic calibration"},
{"en","ui.autosave","Changes are saved automatically"},
{"en","ui.calibration","Calibration"},
{"en","ui.close","Close"},
{"en","ui.controller","Controller"},
{"en","ui.controller.disconnected","Selected controller disconnected"},
{"en","ui.controller.none","No controller connected"},
{"en","ui.invert.roll.short","Roll"},
{"en","ui.invert.short","Invert"},
{"en","ui.invert.yaw.short","Yaw"},
{"en","ui.language","Language"},
{"en","ui.operation_failed","Operation failed"},
{"en","ui.save_failed","Changes could not be saved"},
{"en","ui.scale.short","Scale"},
{"en","ui.sensor","Gyro sensor"},
{"en","ui.sensor.choose","Select a gyro sensor"},
{"en","ui.sensor.help","Choose the motion sensor that belongs to your controller."},
{"en","ui.sensor.none","Controller's default sensor"},
{"en","ui.short_press.short","Tap only"},
{"en","ui.source","Source"},
{"en","ui.source.waiting","Waiting for usable motion"},
{"en","ui.temporary_settings","Temporary settings"},
{"en","ui.threshold.short","Threshold"},
{"en","unavailable","Unavailable"},
{"en","unknown","Unknown"},
{"en","warning.double","In Steam, turn off gyro-to-mouse and gyro-to-stick to avoid moving twice."},
{"es","Acceleration","ACELERACIÓN"},
{"es","ActivationMode","MODO DE ACTIVACIÓN"},
{"es","AimMultiplier","MULTIPLICADOR AL APUNTAR"},
{"es","AltFireMultiplier","MULTIPLICADOR DEL DISPARO ALTERNATIVO"},
{"es","AutomaticCalibration","CALIBRACIÓN"},
{"es","FlickSpinDurationMs","DURACIÓN DEL GIRO"},
{"es","FlickStick","FLICK STICK"},
{"es","GyroButton","BOTONES"},
{"es","GyroEnabled","GIROSCOPIO"},
{"es","GyroGripSensor","SENSOR DE AGARRE"},
{"es","GyroSpace","ESPACIO DEL GIROSCOPIO"},
{"es","GyroStick","STICK"},
{"es","GyroStickSensor","SENSOR DE STICK"},
{"es","GyroTouchpad","PANEL TÁCTIL"},
{"es","InvertX","INVERTIR X"},
{"es","InvertY","INVERTIR Y"},
{"es","SensitivityX","SENSIBILIDAD X"},
{"es","SensitivityY","SENSIBILIDAD Y"},
{"es","Smoothing","SUAVIZADO"},
{"es","acceleration.high","Alto (3x)"},
{"es","acceleration.low","Bajo (1,5x)"},
{"es","acceleration.medium","Medio (2x)"},
{"es","calibration.action","RECALIBRAR GIROSCOPIO"},
{"es","calibration.steamHelp","Para recalibrar este mando, utiliza los ajustes de mando de Steam."},
{"es","choice.activation.off","Desactiva el movimiento con giroscopio."},
{"es","description.Acceleration","Gira más rápido con movimientos rápidos y conserva la precisión en los lentos."},
{"es","description.AimMultiplier","Multiplica la sensibilidad del giroscopio al apuntar."},
{"es","description.AltFireMultiplier","Ajusta la sensibilidad del giroscopio durante el disparo alternativo."},
{"es","description.AutomaticCalibration","Elige cuándo corregir los movimientos que aparecen con el mando inmóvil."},
{"es","description.FlickSpinDurationMs","Tiempo que tarda el giro inicial. A 0 ms, el giro es instantáneo."},
{"es","description.GyroButton","Elige el botón que controla el giroscopio."},
{"es","description.GyroEnabled","Controla la cámara o el cursor girando el mando."},
{"es","description.GyroGripSensor","Controla el giroscopio tocando la empuñadura."},
{"es","description.GyroStick","Controla el giroscopio inclinando el stick."},
{"es","description.GyroStickSensor","Controla el giroscopio apoyando un dedo en el stick, sin hacer clic."},
{"es","description.GyroTouchpad","Controla el giroscopio tocando el panel táctil."},
{"es","description.InvertX","Invierte el movimiento horizontal del giroscopio."},
{"es","description.InvertY","Invierte el movimiento vertical del giroscopio."},
{"es","description.SensitivityX","Cuánto se mueve la vista o el cursor a izquierda y derecha al girar el mando."},
{"es","description.SensitivityY","Cuánto se mueve la vista o el cursor arriba y abajo al inclinar el mando."},
{"es","description.Smoothing","Suaviza pequeños temblores. Los movimientos rápidos siguen siendo inmediatos. Cero lo desactiva."},
{"es","description.calibration.cancel","Detén la calibración en curso."},
{"es","high","Alto"},
{"es","low","Bajo"},
{"es","medium","Medio"},
{"es","mode.aim","Solo al apuntar"},
{"es","mode.always","Siempre activo"},
{"es","mode.hip","Solo sin apuntar"},
{"es","mode.hold","Mantener para activar"},
{"es","mode.hold_disable","Mantener para desactivar"},
{"es","mode.toggle","Alternar"},
{"es","none","Ninguno"},
{"es","off","Desactivado"},
{"es","on","Activado"},
{"es","page","CONFIGURACIÓN DE GIROSCOPIO"},
{"es","space.player","Espacio del jugador"},
{"es","space.roll","Alabeo local"},
{"es","space.world","Espacio del mundo"},
{"es","space.yaw","Guiñada local"},
{"es","ui.activators","ACTIVADORES"},
{"fr","Acceleration","ACCÉLÉRATION"},
{"fr","ActivationMode","MODE D'ACTIVATION"},
{"fr","AimMultiplier","MULTIPLICATEUR EN VISÉE"},
{"fr","AltFireMultiplier","MULTIPLICATEUR DU TIR SECONDAIRE"},
{"fr","AutomaticCalibration","CALIBRATION"},
{"fr","FastSensX","SENSIBILITÉ RAPIDE X"},
{"fr","FastSensY","SENSIBILITÉ RAPIDE Y"},
{"fr","FastSpeed","ACCÉLÉRATION MAXIMALE"},
{"fr","FlickExponent","RACCOURCIR LES PETITS PIVOTS"},
{"fr","FlickForward","TOLÉRANCE VERS L'AVANT"},
{"fr","FlickPadInner","SEUIL DE RETOUR DU PAVÉ"},
{"fr","FlickPadOuter","SEUIL DE DÉPART DU PAVÉ"},
{"fr","FlickSmoothAngle","LIMITE DES PETITES ROTATIONS"},
{"fr","FlickSmoothSpeed","LIMITE DU LISSAGE"},
{"fr","FlickSmoothing","LISSAGE DES PETITES ROTATIONS"},
{"fr","FlickSnap","DIRECTIONS DU PIVOT"},
{"fr","FlickSnapStrength","FORCE DU GUIDAGE"},
{"fr","FlickSpinDurationMs","DURÉE DU PIVOT"},
{"fr","FlickStick","FLICK STICK"},
{"fr","FlickStickInner","SEUIL DE RETOUR DU STICK"},
{"fr","FlickStickOuter","SEUIL DE DÉPART DU STICK"},
{"fr","FlickStyle","COMPORTEMENT DU FLICK"},
{"fr","GyroButton","BOUTONS"},
{"fr","GyroEnabled","GYROSCOPE"},
{"fr","GyroGripSensor","CAPTEUR DE POIGNÉE"},
{"fr","GyroSpace","REPÈRE DU GYROSCOPE"},
{"fr","GyroStick","STICK"},
{"fr","GyroStickSensor","CAPTEUR DE STICK"},
{"fr","GyroTouchpad","PAVÉ TACTILE"},
{"fr","GyroTrigger","GÂCHETTES"},
{"fr","HoldInvert","INVERSION TEMPORAIRE"},
{"fr","HoldTrackball","TRACKBALL GYRO"},
{"fr","InvertRoll","INVERSER LE ROULIS"},
{"fr","InvertX","INVERSER X"},
{"fr","InvertY","INVERSER Y"},
{"fr","InvertYaw","INVERSER LE LACET"},
{"fr","LocalAxisAngle","INCLINAISON DE L'AXE PRINCIPAL"},
{"fr","LocalRollContribution","CONTRIBUTION DU ROLL COMPLÉMENTAIRE"},
{"fr","RecenterButton","RECENTRER LA CAMÉRA"},
{"fr","RightStickThreshold","SEUIL D'INCLINAISON DU STICK"},
{"fr","SensitivityX","SENSIBILITÉ X"},
{"fr","SensitivityY","SENSIBILITÉ Y"},
{"fr","ShortPress","APPUI COURT SEUL"},
{"fr","SlowSensitivityX","SENSIBILITÉ LENTE X"},
{"fr","SlowSensitivityY","SENSIBILITÉ LENTE Y"},
{"fr","SlowSpeed","DÉBUT DE L'ACCÉLÉRATION"},
{"fr","SmoothThreshold","LIMITE DU LISSAGE"},
{"fr","Smoothing","LISSAGE"},
{"fr","StickEffect","EFFET DU STICK DROIT"},
{"fr","TemporaryInvertAxes","AXES INVERSÉS"},
{"fr","TemporaryInvertButton","INVERSION TEMPORAIRE"},
{"fr","Tightening","STABILISATION DES PETITS MOUVEMENTS"},
{"fr","TrackballAxes","AXES DU TRACKBALL"},
{"fr","TrackballButton","TRACKBALL GYRO"},
{"fr","TrackballDecay","RALENTISSEMENT DU TRACKBALL"},
{"fr","TriggerThreshold","SEUIL DES GÂCHETTES"},
{"fr","UIScale","TAILLE DE L'INTERFACE"},
{"fr","ZoomCompensation","ADAPTER AU ZOOM"},
{"fr","acceleration.high","Forte (3x)"},
{"fr","acceleration.low","Faible (1,5x)"},
{"fr","acceleration.medium","Moyenne (2x)"},
{"fr","anytime","À tout moment"},
{"fr","automatic","Automatique"},
{"fr","axes.both","Les deux"},
{"fr","axes.x","Horizontal"},
{"fr","axes.y","Vertical"},
{"fr","both","Les deux"},
{"fr","button.26","Bouton 26"},
{"fr","button.27","Bouton 27"},
{"fr","button.28","Bouton 28"},
{"fr","button.29","Bouton 29"},
{"fr","button.30","Bouton 30"},
{"fr","button.31","Bouton 31"},
{"fr","button.and"," + "},
{"fr","button.back","Retour"},
{"fr","button.down","Croix bas"},
{"fr","button.east","Bouton de droite"},
{"fr","button.guide","Guide"},
{"fr","button.left","Croix gauche"},
{"fr","button.left_click","Clic du stick gauche"},
{"fr","button.left_rear1","Arrière gauche 1"},
{"fr","button.left_rear2","Arrière gauche 2"},
{"fr","button.left_shoulder","Épaule gauche"},
{"fr","button.misc1","Supplémentaire 1"},
{"fr","button.misc2","Supplémentaire 2"},
{"fr","button.misc3","Supplémentaire 3"},
{"fr","button.misc4","Supplémentaire 4"},
{"fr","button.misc5","Supplémentaire 5"},
{"fr","button.misc6","Supplémentaire 6"},
{"fr","button.north","Bouton du haut"},
{"fr","button.or"," ou "},
{"fr","button.rear1.both","Les deux boutons arrière principaux"},
{"fr","button.rear1.either","L'un ou l'autre bouton arrière principal"},
{"fr","button.rear2.both","Les deux boutons arrière secondaires"},
{"fr","button.rear2.either","L'un ou l'autre bouton arrière secondaire"},
{"fr","button.right","Croix droite"},
{"fr","button.right_click","Clic du stick droit"},
{"fr","button.right_rear1","Arrière droit 1"},
{"fr","button.right_rear2","Arrière droit 2"},
{"fr","button.right_shoulder","Épaule droite"},
{"fr","button.shoulders.both","Les deux boutons d'épaule"},
{"fr","button.shoulders.either","L'un ou l'autre bouton d'épaule"},
{"fr","button.south","Bouton du bas"},
{"fr","button.start","Démarrer"},
{"fr","button.sticks.both","Les deux clics de stick"},
{"fr","button.sticks.either","L'un ou l'autre clic de stick"},
{"fr","button.touchpad","Clic du pavé tactile"},
{"fr","button.up","Croix haut"},
{"fr","button.west","Bouton de gauche"},
{"fr","calibration.action","Recalibrer le gyroscope"},
{"fr","calibration.collecting","Calibration en cours - restez immobile"},
{"fr","calibration.complete","Calibration terminée"},
{"fr","calibration.countdown","Calibration dans"},
{"fr","calibration.moving","Mouvement détecté - restez immobile pour réessayer"},
{"fr","calibration.steamHelp","Calibrez cette manette dans les paramètres de manette Steam."},
{"fr","cancel","Annuler la calibration"},
{"fr","choice.acceleration.custom","La sensibilité suit les valeurs lente et rapide que vous avez choisies."},
{"fr","choice.acceleration.high","Les rotations rapides sont jusqu'à trois fois plus sensibles."},
{"fr","choice.acceleration.low","Les rotations rapides sont jusqu'à 1,5 fois plus sensibles."},
{"fr","choice.acceleration.medium","Les rotations rapides sont jusqu'à deux fois plus sensibles."},
{"fr","choice.acceleration.off","Gardez la même sensibilité quelle que soit la vitesse."},
{"fr","choice.activation.always","Le gyro reste actif."},
{"fr","choice.activation.hold","Maintenez la commande choisie pour activer le gyro."},
{"fr","choice.activation.hold_disable","Maintenez la commande choisie pour désactiver le gyro."},
{"fr","choice.activation.off","Désactive la rotation au gyro."},
{"fr","choice.activation.toggle","Utilisez la commande choisie pour activer ou désactiver le gyro."},
{"fr","choice.axes.both","Horizontal et vertical."},
{"fr","choice.axes.x","Horizontal uniquement."},
{"fr","choice.axes.y","Vertical uniquement."},
{"fr","choice.button.on","Utilisez ce bouton pour contrôler le gyro."},
{"fr","choice.calibration.anytime","Corrigez la dérive dès que la manette est immobile."},
{"fr","choice.calibration.menus","Corrigez la dérive quand la manette est immobile dans un menu."},
{"fr","choice.calibration.off","Conservez la calibration actuelle."},
{"fr","choice.flick.both","Utilisez le stick droit ou le pavé tactile droit pour tourner rapidement."},
{"fr","choice.flick.full","Inclinez pour pivoter, puis tournez en cercle pour orienter la caméra."},
{"fr","choice.flick.off","Désactivez le Flick Stick."},
{"fr","choice.flick.on","Poussez le stick droit dans une direction pour lui faire face, puis faites-le tourner sur le bord pour continuer à tourner."},
{"fr","choice.flick.pivot_only","Inclinez pour pivoter. Les mouvements circulaires ne tournent pas la caméra."},
{"fr","choice.flick.rotate_only","Commencez à tourner en cercle sans pivot initial."},
{"fr","choice.flick.snap45","Oriente les pivots vers huit directions, diagonales comprises."},
{"fr","choice.flick.snap90","Oriente les pivots vers l'avant, l'arrière, la gauche ou la droite."},
{"fr","choice.flick.snap_off","Utilise la direction exacte que vous indiquez."},
{"fr","choice.flick.touchpad","Touchez à distance du centre du pavé tactile droit pour vous orienter, puis décrivez un cercle pour continuer à tourner."},
{"fr","choice.side.both","Utilisez les deux côtés en même temps."},
{"fr","choice.side.either","Un seul côté suffit."},
{"fr","choice.side.left","Utilisez le côté gauche."},
{"fr","choice.side.off","N'utilisez pas cette commande."},
{"fr","choice.side.right","Utilisez le côté droit."},
{"fr","choice.space.laser","Pointez l'avant de la manette comme un pointeur laser."},
{"fr","choice.space.local","Ajustez comment les rotations et les inclinaisons de la manette font tourner la vue."},
{"fr","choice.space.player","Tournez à gauche ou à droite par rapport au sol. Inclinez la manette vers l'avant ou l'arrière pour regarder en haut ou en bas."},
{"fr","choice.space.player_lean","Inclinez la manette sur le côté pour tourner. Basculez-la vers l'avant ou l'arrière pour regarder en haut ou en bas."},
{"fr","choice.space.roll","Tournez à gauche ou à droite avec l'avant de la manette pointé vers le haut."},
{"fr","choice.space.world","Garde les mouvements alignés avec le sol. Regarder en haut ou en bas devient plus difficile avec la manette sur le côté."},
{"fr","choice.space.world_lean","Inclinez la manette sur le côté pour tourner, avec une visée verticale adaptée à la gravité."},
{"fr","choice.space.yaw","Tournez la manette à gauche ou à droite, comme si elle était posée à plat sur une table."},
{"fr","choice.space.yaw_roll","Combinez les mouvements du lacet et du roulis."},
{"fr","choice.stick.disables","Suspendez le gyro quand le stick droit est incliné."},
{"fr","choice.stick.enables","Activez le gyro quand le stick droit est incliné."},
{"fr","choice.touchpad.single_on","Touchez le pavé tactile pour activer cette commande."},
{"fr","choice.trigger.left","Utilisez la gâchette gauche."},
{"fr","choice.trigger.right","Utilisez la gâchette droite."},
{"fr","context.flick","MODE DE JEU DU FLICK STICK"},
{"fr","context.gyro","MODE DE JEU DU GYRO"},
{"fr","context.none","Choisir un mode"},
{"fr","custom","Personnalisée"},
{"fr","description.Acceleration","Tournez plus vite avec des mouvements rapides, tout en gardant la précision des mouvements lents."},
{"fr","description.ActivationMode","Choisissez quand le gyro est actif."},
{"fr","description.AimMultiplier","Ajustez la sensibilité du gyro pendant la visée."},
{"fr","description.AltFireMultiplier","Ajustez la sensibilité du gyro pendant le tir secondaire."},
{"fr","description.AutomaticCalibration","Choisissez quand corriger les mouvements qui apparaissent alors que la manette est immobile."},
{"fr","description.FastSensX","Sensibilité horizontale des mouvements rapides."},
{"fr","description.FastSensY","Sensibilité verticale des mouvements rapides."},
{"fr","description.FastSpeed","Au-dessus de cette vitesse, utilisez la sensibilité rapide."},
{"fr","description.FlickExponent","Zéro garde la même durée pour tous les pivots. Un donne au pivot de 90° la moitié de la durée d'un pivot de 180°."},
{"fr","description.FlickForward","Pointer dans cet angle autour de l'avant permet de tourner en cercle sans pivot initial."},
{"fr","description.FlickPadInner","Ramenez le doigt à cette distance du centre pour préparer un nouveau pivot."},
{"fr","description.FlickPadOuter","Touchez à cette distance du centre pour commencer un pivot."},
{"fr","description.FlickSmoothAngle","Les changements d'angle supérieurs à cette limite ne sont pas lissés."},
{"fr","description.FlickSmoothSpeed","Les rotations circulaires plus rapides ne sont pas lissées."},
{"fr","description.FlickSmoothing","Adoucit les petits à-coups de la rotation circulaire. Une valeur plus élevée rend la rotation plus douce, mais moins réactive."},
{"fr","description.FlickSnap","Oriente le pivot initial vers des directions fixes."},
{"fr","description.FlickSnapStrength","Zéro conserve votre direction exacte. Un suit entièrement la direction fixe la plus proche."},
{"fr","description.FlickSpinDurationMs","Temps nécessaire pour effectuer le pivot. À 0 ms, il est instantané."},
{"fr","description.FlickStick","Choisissez la commande utilisée pour tourner rapidement."},
{"fr","description.FlickStickInner","Ramenez le stick à cette distance du centre pour préparer un nouveau pivot."},
{"fr","description.FlickStickOuter","Éloignez le stick du centre de cette distance pour commencer un pivot."},
{"fr","description.FlickStyle","Choisissez le pivot initial, la rotation circulaire ou les deux."},
{"fr","description.GyroButton","Choisissez le bouton qui contrôle le gyro."},
{"fr","description.GyroEnabled","Contrôlez la caméra ou le curseur en tournant la manette."},
{"fr","description.GyroGripSensor","Contrôlez le gyro en touchant la poignée."},
{"fr","description.GyroSpace","Choisissez quels mouvements de la manette font tourner la vue."},
{"fr","description.GyroStick","Contrôlez le gyro en inclinant le stick."},
{"fr","description.GyroStickSensor","Contrôlez le gyro en posant un doigt sur le stick, sans cliquer."},
{"fr","description.GyroTouchpad","Contrôlez le gyro en touchant le pavé tactile."},
{"fr","description.GyroTrigger","Choisissez la gâchette qui contrôle le gyro."},
{"fr","description.HoldInvert","Inversez le sens du gyro pendant le maintien d'un activateur."},
{"fr","description.HoldTrackball","Continuez à tourner pendant le maintien d'un activateur pour replacer la manette."},
{"fr","description.InvertRoll","Inversez la gauche et la droite pour les mouvements de roulis."},
{"fr","description.InvertX","Inversez la gauche et la droite."},
{"fr","description.InvertY","Inversez le haut et le bas."},
{"fr","description.InvertYaw","Inversez la gauche et la droite pour les mouvements de lacet."},
{"fr","description.LocalAxisAngle","Choisissez l'axe de rotation : 0 degré pour le lacet, 90 degrés pour le roulis."},
{"fr","description.LocalRollContribution","Ajoutez plus ou moins du second mouvement de rotation. À 0, seul le mouvement principal agit ; une valeur négative inverse le mouvement ajouté."},
{"fr","description.RecenterButton","Ramenez la caméra à l'horizontale."},
{"fr","description.RightStickThreshold","Inclinaison nécessaire pour que le stick contrôle le gyro."},
{"fr","description.SensitivityX","Distance parcourue vers la gauche ou la droite quand vous tournez la manette."},
{"fr","description.SensitivityY","Distance parcourue vers le haut ou le bas quand vous inclinez la manette."},
{"fr","description.ShortPress","Un appui court déclenche l'action au relâchement. Un maintien bloque cette action."},
{"fr","description.SlowSensitivityX","Sensibilité horizontale des mouvements lents."},
{"fr","description.SlowSensitivityY","Sensibilité verticale des mouvements lents."},
{"fr","description.SlowSpeed","En dessous de cette vitesse, utilisez la sensibilité lente."},
{"fr","description.SmoothThreshold","Les mouvements plus rapides que cette limite ne sont pas lissés."},
{"fr","description.Smoothing","Adoucit les petits tremblements. Une valeur élevée rend les mouvements plus doux, mais moins réactifs. Zéro transmet directement les mouvements."},
{"fr","description.StickEffect","Choisissez l'effet de l'inclinaison du stick droit sur le gyro."},
{"fr","description.TemporaryInvertAxes","Choisissez les directions à inverser."},
{"fr","description.TemporaryInvertButton","Maintenez ce bouton pour inverser le sens du gyro."},
{"fr","description.Tightening","Atténue les petits mouvements sans les bloquer. Zéro désactive cet effet."},
{"fr","description.TrackballAxes","Choisissez les directions qui continuent à tourner."},
{"fr","description.TrackballButton","Maintenez ce bouton pour continuer à tourner pendant que vous replacez la manette."},
{"fr","description.TrackballDecay","Vitesse du ralentissement. Zéro conserve la vitesse ; un la divise par deux chaque seconde."},
{"fr","description.TriggerThreshold","Jusqu'où enfoncer la gâchette pour l'activer."},
{"fr","description.UIScale","Ajustez la taille du menu. Automatique l'adapte à votre écran."},
{"fr","description.ZoomCompensation","Réduisez la sensibilité gyro lorsque vous zoomez."},
{"fr","description.calibration","Posez la manette sur une surface stable et laissez-la immobile jusqu'à la fin de la calibration."},
{"fr","description.calibration.cancel","Arrêtez la calibration en cours."},
{"fr","description.context.flick","Choisissez le mode de jeu qui contrôle le flick stick."},
{"fr","description.context.gyro","Choisissez le mode de jeu qui contrôle le gyro."},
{"fr","description.context.sensitivity","Ajustez la sensibilité du gyro."},
{"fr","description.reset","Rétablissez les valeurs par défaut de tous les réglages."},
{"fr","description.save","Sauvegardez vos réglages."},
{"fr","description.tab.default","Réglages du gyro et du flick stick."},
{"fr","description.tab.general","Réglages de la manette et de la calibration."},
{"fr","either","L'un ou l'autre"},
{"fr","flick.both","L'un ou l'autre"},
{"fr","flick.full","Pivot et rotation"},
{"fr","flick.pivot_only","Pivot uniquement"},
{"fr","flick.rotate_only","Rotation uniquement"},
{"fr","flick.snap45","Directions à 45°"},
{"fr","flick.snap90","Directions à 90°"},
{"fr","flick.stick","Stick"},
{"fr","flick.touchpad","Pavé tactile"},
{"fr","high","Élevé"},
{"fr","left","Gauche"},
{"fr","low","Faible"},
{"fr","medium","Moyen"},
{"fr","menus","Menus uniquement"},
{"fr","mode.aim","En visée uniquement"},
{"fr","mode.always","Toujours actif"},
{"fr","mode.context","Uniquement dans ce mode"},
{"fr","mode.hip","Hors visée uniquement"},
{"fr","mode.hold","Maintenir pour activer"},
{"fr","mode.hold_disable","Maintenir pour désactiver"},
{"fr","mode.outside_context","Sauf dans ce mode"},
{"fr","mode.toggle","Basculer"},
{"fr","none","Aucun"},
{"fr","off","Désactivé"},
{"fr","on","Activé"},
{"fr","page","CONFIGURATION GYRO"},
{"fr","reset","Tout réinitialiser"},
{"fr","right","Droite"},
{"fr","save","Sauvegarder"},
{"fr","space.laser","Pointeur laser"},
{"fr","space.local","Local Space (avancé)"},
{"fr","space.player","Repère du joueur"},
{"fr","space.player_lean","Player Space - Inclinaison"},
{"fr","space.roll","Roulis local"},
{"fr","space.world","Repère du monde"},
{"fr","space.world_lean","World Space - Inclinaison"},
{"fr","space.yaw","Lacet local"},
{"fr","space.yaw_roll","Yaw + Roll"},
{"fr","stick.disables","Désactiver le gyro"},
{"fr","stick.enables","Activer le gyro"},
{"fr","tab.default","Caméra"},
{"fr","tab.general","Général"},
{"fr","tab.unavailable","Ce mode est actuellement indisponible."},
{"fr","trigger.left","Gâchette gauche"},
{"fr","trigger.right","Gâchette droite"},
{"fr","ui.activators","ACTIVATEURS"},
{"fr","ui.advanced","Avancé"},
{"fr","ui.advanced.acceleration","Options d'accélération."},
{"fr","ui.advanced.flick","Options du Flick Stick."},
{"fr","ui.advanced.hold_disable","Inversion temporaire et trackball gyro."},
{"fr","ui.advanced.modifiers","Options du stick droit."},
{"fr","ui.advanced.smoothing","Options de lissage et de stabilisation."},
{"fr","ui.auto_calibration","Calibration automatique"},
{"fr","ui.autosave","Sauvegarde automatique des changements"},
{"fr","ui.calibration","Calibration"},
{"fr","ui.close","Fermer"},
{"fr","ui.controller","Manette"},
{"fr","ui.controller.disconnected","Manette sélectionnée déconnectée"},
{"fr","ui.controller.none","Aucune manette connectée"},
{"fr","ui.invert.roll.short","Roulis"},
{"fr","ui.invert.short","Inverser"},
{"fr","ui.invert.yaw.short","Lacet"},
{"fr","ui.language","Langue"},
{"fr","ui.operation_failed","Échec de l'opération"},
{"fr","ui.save_failed","Impossible de sauvegarder les changements"},
{"fr","ui.scale.short","Échelle"},
{"fr","ui.sensor","Capteur gyro"},
{"fr","ui.sensor.choose","Choisir un capteur gyro"},
{"fr","ui.sensor.help","Choisissez le capteur de mouvement de votre manette."},
{"fr","ui.sensor.none","Capteur habituel de la manette"},
{"fr","ui.short_press.short","Appui court"},
{"fr","ui.source","Source"},
{"fr","ui.source.waiting","En attente de données de mouvement"},
{"fr","ui.temporary_settings","Réglages temporaires"},
{"fr","ui.threshold.short","Seuil"},
{"fr","unavailable","Indisponible"},
{"fr","unknown","Inconnu"},
{"fr","warning.double","Dans Steam, désactivez le gyro souris et le gyro stick pour éviter de doubler les mouvements."},
{"it","Acceleration","ACCELERAZIONE"},
{"it","ActivationMode","MODALITÀ DI ATTIVAZIONE"},
{"it","AimMultiplier","MOLTIPLICATORE DI MIRA"},
{"it","AltFireMultiplier","MOLTIPLICATORE FUOCO ALTERNATIVO"},
{"it","AutomaticCalibration","CALIBRAZIONE"},
{"it","FlickSpinDurationMs","DURATA ROTAZIONE"},
{"it","FlickStick","FLICK STICK"},
{"it","GyroButton","PULSANTI"},
{"it","GyroEnabled","GIROSCOPIO"},
{"it","GyroGripSensor","SENSORE IMPUGNATURA"},
{"it","GyroSpace","SPAZIO DEL GIROSCOPIO"},
{"it","GyroStick","STICK"},
{"it","GyroStickSensor","SENSORE STICK"},
{"it","GyroTouchpad","TOUCHPAD"},
{"it","InvertX","INVERTI X"},
{"it","InvertY","INVERTI Y"},
{"it","SensitivityX","SENSIBILITÀ X"},
{"it","SensitivityY","SENSIBILITÀ Y"},
{"it","Smoothing","SMUSSAMENTO"},
{"it","acceleration.high","Alto (3x)"},
{"it","acceleration.low","Basso (1,5x)"},
{"it","acceleration.medium","Medio (2x)"},
{"it","calibration.action","RICALIBRA GIROSCOPIO"},
{"it","calibration.steamHelp","Per ricalibrare questo controller, usa le impostazioni controller di Steam."},
{"it","choice.activation.off","Disattiva il movimento con il giroscopio."},
{"it","description.Acceleration","Gira più velocemente con movimenti rapidi e mantieni la precisione con quelli lenti."},
{"it","description.AimMultiplier","Moltiplica la sensibilità del giroscopio durante la mira."},
{"it","description.AltFireMultiplier","Regola la sensibilità del giroscopio durante il fuoco alternativo."},
{"it","description.AutomaticCalibration","Scegli quando correggere i movimenti che compaiono mentre il controller è fermo."},
{"it","description.FlickSpinDurationMs","Tempo necessario per la rotazione iniziale. A 0 ms, la rotazione è istantanea."},
{"it","description.GyroButton","Scegli il pulsante che controlla il giroscopio."},
{"it","description.GyroEnabled","Controlla la visuale o il cursore ruotando il controller."},
{"it","description.GyroGripSensor","Controlla il giroscopio toccando l'impugnatura."},
{"it","description.GyroStick","Controlla il giroscopio inclinando lo stick."},
{"it","description.GyroStickSensor","Controlla il giroscopio appoggiando un dito sullo stick, senza premere."},
{"it","description.GyroTouchpad","Controlla il giroscopio toccando il touchpad."},
{"it","description.InvertX","Inverti il movimento orizzontale del giroscopio."},
{"it","description.InvertY","Inverti il movimento verticale del giroscopio."},
{"it","description.SensitivityX","Quanto si sposta la visuale o il cursore a sinistra e a destra quando ruoti il controller."},
{"it","description.SensitivityY","Quanto si sposta la visuale o il cursore in alto e in basso quando inclini il controller."},
{"it","description.Smoothing","Attenua i piccoli tremori. I movimenti rapidi restano immediati. Zero disattiva il filtro."},
{"it","description.calibration.cancel","Interrompi la calibrazione in corso."},
{"it","high","Alto"},
{"it","low","Basso"},
{"it","medium","Medio"},
{"it","mode.aim","Solo durante la mira"},
{"it","mode.always","Sempre attivo"},
{"it","mode.hip","Solo senza mirare"},
{"it","mode.hold","Tieni premuto per attivare"},
{"it","mode.hold_disable","Tieni premuto per disattivare"},
{"it","mode.toggle","Alterna"},
{"it","none","Nessuno"},
{"it","off","Disattivo"},
{"it","on","Attivo"},
{"it","page","CONFIGURAZIONE GIROSCOPIO"},
{"it","space.player","Spazio giocatore"},
{"it","space.roll","Rollio locale"},
{"it","space.world","Spazio globale"},
{"it","space.yaw","Imbardata locale"},
{"it","ui.activators","ATTIVATORI"},
{"pt","Acceleration","ACELERAÇÃO"},
{"pt","ActivationMode","MODO DE ATIVAÇÃO"},
{"pt","AimMultiplier","MULTIPLICADOR DE MIRA"},
{"pt","AltFireMultiplier","MULTIPLICADOR DE DISPARO ALTERNATIVO"},
{"pt","AutomaticCalibration","CALIBRAÇÃO"},
{"pt","FlickSpinDurationMs","DURAÇÃO DO GIRO"},
{"pt","FlickStick","FLICK STICK"},
{"pt","GyroButton","BOTÕES"},
{"pt","GyroEnabled","GIROSCÓPIO"},
{"pt","GyroGripSensor","SENSOR DE PEGA"},
{"pt","GyroSpace","ESPAÇO DO GIROSCÓPIO"},
{"pt","GyroStick","ANALÓGICO"},
{"pt","GyroStickSensor","SENSOR DO ANALÓGICO"},
{"pt","GyroTouchpad","PAINEL TÁTIL"},
{"pt","InvertX","INVERTER X"},
{"pt","InvertY","INVERTER Y"},
{"pt","SensitivityX","SENSIBILIDADE X"},
{"pt","SensitivityY","SENSIBILIDADE Y"},
{"pt","Smoothing","SUAVIZAÇÃO"},
{"pt","acceleration.high","Alto (3x)"},
{"pt","acceleration.low","Baixo (1,5x)"},
{"pt","acceleration.medium","Médio (2x)"},
{"pt","calibration.action","RECALIBRAR GIROSCÓPIO"},
{"pt","calibration.steamHelp","Para recalibrar este comando, utiliza as definições de comando do Steam."},
{"pt","choice.activation.off","Desativa o movimento com giroscópio."},
{"pt","description.Acceleration","Gire mais rápido com movimentos rápidos e mantenha a precisão nos movimentos lentos."},
{"pt","description.AimMultiplier","Multiplica a sensibilidade do giroscópio ao mirar."},
{"pt","description.AltFireMultiplier","Ajuste a sensibilidade do giroscópio durante o disparo alternativo."},
{"pt","description.AutomaticCalibration","Escolha quando corrigir movimentos que aparecem com o controle parado."},
{"pt","description.FlickSpinDurationMs","Tempo necessário para o giro inicial. Em 0 ms, o giro é instantâneo."},
{"pt","description.GyroButton","Escolha o botão que controla o giroscópio."},
{"pt","description.GyroEnabled","Controle a câmera ou o cursor girando o controle."},
{"pt","description.GyroGripSensor","Controle o giroscópio tocando na pega."},
{"pt","description.GyroStick","Controle o giroscópio inclinando o analógico."},
{"pt","description.GyroStickSensor","Controle o giroscópio apoiando um dedo no analógico, sem clicar."},
{"pt","description.GyroTouchpad","Controle o giroscópio tocando no painel tátil."},
{"pt","description.InvertX","Inverte o movimento horizontal do giroscópio."},
{"pt","description.InvertY","Inverte o movimento vertical do giroscópio."},
{"pt","description.SensitivityX","Quanto a câmera ou o cursor se move para a esquerda e a direita ao girar o controle."},
{"pt","description.SensitivityY","Quanto a câmera ou o cursor se move para cima e para baixo ao inclinar o controle."},
{"pt","description.Smoothing","Suaviza pequenos tremores. Movimentos rápidos continuam imediatos. Zero desativa o filtro."},
{"pt","description.calibration.cancel","Interrompa a calibração em andamento."},
{"pt","high","Alto"},
{"pt","low","Baixo"},
{"pt","medium","Médio"},
{"pt","mode.aim","Somente ao mirar"},
{"pt","mode.always","Sempre ativo"},
{"pt","mode.hip","Somente sem mirar"},
{"pt","mode.hold","Segurar para ativar"},
{"pt","mode.hold_disable","Segurar para desativar"},
{"pt","mode.toggle","Alternar"},
{"pt","none","Nenhum"},
{"pt","off","Desativado"},
{"pt","on","Ativado"},
{"pt","page","CONFIGURAÇÃO DO GIROSCÓPIO"},
{"pt","space.player","Espaço do jogador"},
{"pt","space.roll","Rolagem local"},
{"pt","space.world","Espaço global"},
{"pt","space.yaw","Guinada local"},
{"pt","ui.activators","ATIVADORES"},
};
static const char* find_text(std::string_view language,const char* key) {
    const Text wanted{language.data(),key,nullptr};
    const auto it=std::lower_bound(std::begin(texts),std::end(texts),wanted,
        [language](const Text& text,const Text& value) {
            const int order=std::string_view(text.language).compare(language);
            return order<0 || (order==0 && std::strcmp(text.key,value.key)<0);
        });
    return it!=std::end(texts) && language==it->language && std::strcmp(key,it->key)==0 ? it->value : nullptr;
}
const char* translate(std::string_view language,const char* key) {
    if(!key)return "?";
    if(const auto* value=find_text(language,key))return value;
    if(language!="en")if(const auto* value=find_text("en",key))return value;
    return "?";
}
}
